name: Update AUTHORS
on:
  push:
    branches:
      - development
jobs:
  createpull_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0S
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
