name: Create main branch pull request
on:
  push:
    branches:
      - development
jobs:
  createPullOnMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reset main branch
        run: |
          git fetch origin development
          git reset --hard development
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main